[package]
name = "tictactoe-rs"
version = "1.0.0"
authors = ["3quarterscolon"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
